version: '2'
volumes:
  google_assistant_credentials_data:
services:
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
  google_assistant:
      build: ./google_assistant
      restart: always
      network_mode: host
      privileged: true
      volumes:
        - 'google_assistant_credentials_data:/root/.config/google-oauthlib-tool'
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  photos:
    privileged: true
    restart: always
    build: ./photos
    ports:
      - "8888:8888"